import React,{useCallback,useEffect,useState}from'react';import{useAuth}from'../auth/AuthContext.jsx';import{go}from'../app/router.js';import{GoogleAuthButton,TelegramAuthButton,PhoneOtpPanel}from'../components/AuthMethods.jsx';import{Icon}from'../components/icons.jsx';
function AuthCard({mode,next}){const{api,login,register,loginWithGoogle,loginWithTelegram,requestPhoneOtp,loginWithPhone}=useAuth();const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[options,setOptions]=useState(null);const isRegister=mode==='register';
 useEffect(()=>{api.request('/v1/customer/auth/options',{auth:false}).then(d=>setOptions(d.data.auth)).catch(e=>setError(e.message))},[api]);
 const done=()=>go(next||'/');const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{if(isRegister)await register({email,password,displayName:name});else await login({email,password});done()}catch(err){setError(err.message)}finally{setBusy(false)}};
 const google=useCallback(async credential=>{setError('');try{await loginWithGoogle(credential);done()}catch(e){setError(e.message)}},[loginWithGoogle,next]);
 const telegram=useCallback(async payload=>{setError('');try{await loginWithTelegram(payload);done()}catch(e){setError(e.message)}},[loginWithTelegram,next]);
 const phoneVerify=async payload=>{await loginWithPhone(payload);done()};const methods=options?.methods;
 return <section className="auth-page auth-page-v08"><div className="auth-card"><span className="eyebrow">Customer account</span><h1>{isRegister?'Create your account':'Welcome back'}</h1><p>{isRegister?'Choose a secure sign-up method. Your account works across this merchant’s stores.':'Choose one of the login methods enabled by this store.'}</p>
  {methods?.google?.enabled&&<GoogleAuthButton clientId={methods.google.client_id} onCredential={google}/>} {methods?.telegram?.enabled&&<TelegramAuthButton botUsername={methods.telegram.bot_username} onAuth={telegram}/>} {methods?.phone?.enabled&&<PhoneOtpPanel countries={methods.phone.countries} onRequest={requestPhoneOtp} onVerify={phoneVerify}/>} 
  {methods?.email_password?.enabled&&<><div className="auth-divider"><span>or use email</span></div><form onSubmit={submit}>{isRegister&&<label>Display name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label>}<label><span><Icon name="mail" size={15}/> Email</span><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label><span><Icon name="lock" size={15}/> Password</span><input required type="password" minLength="12" maxLength="128" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={isRegister?'new-password':'current-password'}/><small>Minimum 12 characters.</small></label><button className="btn btn-primary btn-full" disabled={busy}>{busy?'Please wait…':isRegister?'Create account':'Sign in'}</button></form></>}
  {error&&<div className="form-error">{error}</div>}{!options&&!error&&<small className="muted">Loading sign-in methods…</small>}{methods?.email_password?.enabled&&<div className="auth-switch">{isRegister?'Already have an account?':'New customer?'} <button onClick={()=>go(isRegister?'/login':'/register',{next})}>{isRegister?'Sign in':'Create account'}</button></div>}
 </div></section>;
}
export function LoginPage({next}){return <AuthCard mode="login" next={next}/>;}export function RegisterPage({next}){return <AuthCard mode="register" next={next}/>;}
