import React,{useEffect,useMemo,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{useCart}from'../cart/CartContext.jsx';
import{useStore}from'../store/StoreContext.jsx';
import{Spinner,Empty,money,Toast,Badge}from'../components/UI.jsx';
import{SupportLauncher}from'../components/SupportLauncher.jsx';
import{go}from'../app/router.js';

const emptyAddress={recipient_name:'',phone:'',country_code:'',state:'',city:'',postal_code:'',address_line_1:'',address_line_2:'',delivery_note:''};
const fromSaved=a=>({recipient_name:a?.recipient_name||'',phone:a?.phone||'',country_code:a?.country_code||'',state:a?.state||'',city:a?.city||'',postal_code:a?.postal_code||'',address_line_1:a?.address_line_1||'',address_line_2:a?.address_line_2||'',delivery_note:a?.delivery_note||''});

export function CheckoutPage(){
 const{api,isAuthenticated}=useAuth();const{cart,refresh,setCart}=useCart();const{tenant,publicApi}=useStore();
 const[paymentMethods,setPaymentMethods]=useState([]),[deliveryMethods,setDeliveryMethods]=useState([]),[savedAddresses,setSavedAddresses]=useState([]);
 const[payment,setPayment]=useState(''),[delivery,setDelivery]=useState(''),[promo,setPromo]=useState(''),[note,setNote]=useState('');
 const[address,setAddress]=useState(emptyAddress),[addressMode,setAddressMode]=useState('manual'),[selectedAddress,setSelectedAddress]=useState('');
 const[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[toast,setToast]=useState('');
 const needsAddress=useMemo(()=>cart?.items?.some(i=>['SHIPPING','LOCAL_DELIVERY'].includes(i.fulfillment_mode)),[cart]);
 const physicalMode=cart?.items?.find(i=>['SHIPPING','LOCAL_DELIVERY','PICKUP'].includes(i.fulfillment_mode))?.fulfillment_mode;
 useEffect(()=>{if(!isAuthenticated){setLoading(false);return;}Promise.all([refresh(),publicApi.request('/v1/storefront/payment-methods'),publicApi.request('/v1/storefront/delivery-methods'),api.request('/v1/customer/me/addresses',{auth:true})]).then(([c,p,d,a])=>{setPaymentMethods(p.data.payment_methods||[]);setDeliveryMethods(d.data.delivery_methods||[]);setPayment(p.data.payment_methods?.[0]?.id||'');const match=(d.data.delivery_methods||[]).find(x=>x.fulfillment_mode===c?.items?.find(i=>['SHIPPING','LOCAL_DELIVERY','PICKUP'].includes(i.fulfillment_mode))?.fulfillment_mode);setDelivery(match?.id||'');const addresses=a.data.addresses||[];setSavedAddresses(addresses);const preferred=addresses.find(x=>x.is_default)||addresses[0];if(preferred){setAddressMode('saved');setSelectedAddress(preferred.id);setAddress(fromSaved(preferred));}}).catch(e=>setToast(e.message)).finally(()=>setLoading(false));},[isAuthenticated]);
 if(!isAuthenticated)return <section className="section"><Empty title="Sign in to checkout" action={<button className="btn btn-primary" onClick={()=>go('/login',{next:'/checkout'})}>Sign in</button>}/></section>;
 if(loading)return <Spinner/>;
 if(!cart?.items?.length)return <section className="section"><Empty title="Your cart is empty" action={<button className="btn btn-primary" onClick={()=>go('/explore')}>Explore</button>}/></section>;
 const eligibleDelivery=deliveryMethods.filter(d=>!physicalMode||d.fulfillment_mode===physicalMode);
 const updateAddress=(k,v)=>setAddress(a=>({...a,[k]:v}));
 const chooseSaved=id=>{setSelectedAddress(id);const found=savedAddresses.find(x=>x.id===id);if(found)setAddress(fromSaved(found));};
 const useManual=()=>{setAddressMode('manual');setSelectedAddress('');setAddress(emptyAddress)};
 const submit=async e=>{e.preventDefault();setBusy(true);setToast('');try{const body={idempotency_key:`web-${Date.now()}-${crypto.randomUUID()}`,payment_method_id:payment||undefined,delivery_method_id:delivery||undefined,promotion_code:promo.trim()||undefined,customer_note:note.trim()||undefined,shipping_address:needsAddress?{...address,country_code:address.country_code.toUpperCase()}:undefined};const d=await api.request('/v1/customer/checkout',{method:'POST',body,auth:true});setCart(null);go(`/orders/${encodeURIComponent(d.data.order.id)}`)}catch(err){setToast(err.message)}finally{setBusy(false)}};
 return <section className="section checkout"><div className="section-head"><div><span className="eyebrow">Secure checkout</span><h1>Checkout</h1></div></div><form className="checkout-layout" onSubmit={submit}><div className="checkout-main">
  {needsAddress&&<div className="form-card"><div className="card-title-row"><div><h2>Delivery address</h2><p className="muted">Choose a saved address or enter a different delivery address for this order.</p></div>{addressMode==='saved'&&<button type="button" className="btn btn-secondary btn-small" onClick={useManual}>Use another address</button>}</div>{savedAddresses.length>0&&addressMode==='saved'?<div className="checkout-address-options">{savedAddresses.map(a=><label key={a.id} className={`checkout-address-option ${selectedAddress===a.id?'selected':''}`}><input type="radio" name="saved-address" checked={selectedAddress===a.id} onChange={()=>chooseSaved(a.id)}/><div><div className="address-option-title"><strong>{a.label}</strong>{a.is_default&&<Badge tone="good">Default</Badge>}</div><span>{a.recipient_name}{a.phone?` · ${a.phone}`:''}</span><small>{[a.address_line_1,a.address_line_2,a.city,a.state,a.postal_code,a.country_code].filter(Boolean).join(', ')}</small></div></label>)}<button type="button" className="btn btn-secondary btn-small address-manual-button" onClick={useManual}>Enter a different address</button></div>:<><div className="form-grid"><label>Recipient<input required value={address.recipient_name} onChange={e=>updateAddress('recipient_name',e.target.value)}/></label><label>Phone<input value={address.phone} onChange={e=>updateAddress('phone',e.target.value)}/></label><label>Country code<input required maxLength="2" placeholder="US" value={address.country_code} onChange={e=>updateAddress('country_code',e.target.value.toUpperCase())}/></label><label>State / region<input value={address.state} onChange={e=>updateAddress('state',e.target.value)}/></label><label>City<input required value={address.city} onChange={e=>updateAddress('city',e.target.value)}/></label><label>Postal code<input value={address.postal_code} onChange={e=>updateAddress('postal_code',e.target.value)}/></label><label className="span-2">Address line 1<input required value={address.address_line_1} onChange={e=>updateAddress('address_line_1',e.target.value)}/></label><label className="span-2">Address line 2<input value={address.address_line_2} onChange={e=>updateAddress('address_line_2',e.target.value)}/></label><label className="span-2">Delivery note<textarea value={address.delivery_note} onChange={e=>updateAddress('delivery_note',e.target.value)}/></label></div>{savedAddresses.length>0&&<button type="button" className="link-btn checkout-saved-link" onClick={()=>{setAddressMode('saved');chooseSaved(savedAddresses.find(x=>x.is_default)?.id||savedAddresses[0].id)}}>Choose from saved addresses</button>}</>}</div>}
  {eligibleDelivery.length>0&&<div className="form-card"><h2>Delivery method</h2><div className="select-cards">{eligibleDelivery.map(d=><label key={d.id} className={delivery===d.id?'selected':''}><input type="radio" name="delivery" checked={delivery===d.id} onChange={()=>setDelivery(d.id)}/><div><strong>{d.name}</strong><span>{money(d.flat_fee,tenant?.currency,tenant?.locale)}{d.estimated_min_minutes!=null&&` · ${d.estimated_min_minutes}-${d.estimated_max_minutes} min`}</span></div></label>)}</div></div>}
  <div className="form-card"><h2>Payment</h2><div className="select-cards">{paymentMethods.map(p=><label key={p.id} className={payment===p.id?'selected':''}><input type="radio" name="payment" checked={payment===p.id} onChange={()=>setPayment(p.id)}/><div><strong>{p.name}</strong><span>{p.instructions||p.provider_type}</span></div></label>)}</div></div>
  <div className="form-card"><h2>Discount & note</h2><label>Promotion code<input value={promo} onChange={e=>setPromo(e.target.value)} placeholder="Optional coupon code"/></label><label>Order note<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional note for the merchant"/></label><SupportLauncher placement="checkout"/></div>
 </div><aside className="summary-card checkout-summary"><h3>Your order</h3>{cart.items.map(i=><div className="checkout-line" key={i.public_id}><span>{i.quantity} × {i.title_snapshot}</span><strong>{money(i.line_total,i.currency,tenant?.locale)}</strong></div>)}<hr/><div><span>Subtotal</span><strong>{money(cart.totals.subtotal,cart.currency,tenant?.locale)}</strong></div><p className="summary-hint">Delivery fees and promotion discounts are finalized by the server when you place the order.</p><button className="btn btn-primary btn-full" disabled={busy}>{busy?'Placing order…':'Place order'}</button></aside></form><Toast message={toast} type="bad" onClose={()=>setToast('')}/></section>;
}
