import React,{useEffect,useMemo,useState}from'react';
import{useStore}from'../store/StoreContext.jsx';import{ProductCard}from'../components/ProductCard.jsx';import{ErrorState,Empty,money}from'../components/UI.jsx';import{SupportLauncher}from'../components/SupportLauncher.jsx';import{go}from'../app/router.js';import{SafeImage}from'../components/SafeMedia.jsx';import{ProductGridSkeleton,CategoryStripSkeleton,Skeleton}from'../components/Skeleton.jsx';import{useLocalization}from'../i18n/LocalizationContext.jsx';

export function HomePage(){
 const{tenant,effectiveBranding,experience,publicApi}=useStore();const{t,localizedBranding,localizeCategory,localizeProduct,localizePromotion,localizeSection}=useLocalization();const[categories,setCategories]=useState([]);const[products,setProducts]=useState([]);const[promotions,setPromotions]=useState([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const tasks=[publicApi.request('/v1/storefront/categories'),publicApi.request('/v1/storefront/products',{query:{limit:24}})];if(experience?.features?.promotions!==false)tasks.push(publicApi.request('/v1/storefront/promotions'));const results=await Promise.all(tasks);setCategories(results[0].data.categories||[]);setProducts(results[1].data.products||[]);setPromotions(results[2]?.data?.promotions||[])}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[experience?.features?.promotions]);const sections=useMemo(()=>((experience?.home?.sections||[]).filter(s=>s.enabled!==false)),[experience]);if(loading)return <HomeSkeleton/>;if(error)return <ErrorState code={error} message={error} onRetry={load}/>;
 const render=raw=>{const s=localizeSection(raw);if(s.type==='hero'||s.type==='hero_slider')return <Hero key={s.id} section={s} brand={localizedBranding||effectiveBranding} tenant={tenant} experience={experience} products={products.map(localizeProduct)} t={t}/>;if(s.type==='categories')return <CategorySection key={s.id} section={s} categories={categories.map(localizeCategory)} layout={experience?.layout?.categories} t={t}/>;if(s.type==='promotion_banner'||s.type==='announcement_bar')return <Promo key={s.id} section={s} active={promotions[0]?localizePromotion(promotions[0]):null} tenant={tenant}/>;if(s.type==='new_arrivals'||s.type==='featured_products')return <Products key={s.id} section={s} products={products.map(localizeProduct)} title={s.type==='new_arrivals'?t('home.new_arrivals'):t('home.featured_products')} layout={experience?.layout?.product_grid}/>;return null};
 const defaults=sections.length?sections:[{id:'hero',type:'hero',enabled:true},{id:'categories',type:'categories',enabled:true},{id:'featured',type:'featured_products',enabled:true}];return <>{promotions.length>0&&experience?.features?.promotions!==false&&<ActivePromotionRail promotions={promotions.map(localizePromotion)} tenant={tenant} t={t}/>} {defaults.map(render)}</>;
}
function ActivePromotionRail({promotions,tenant,t}){return <section className="active-promo-rail" aria-label="Current promotions">{promotions.slice(0,3).map(p=><button key={p.id} onClick={()=>go('/explore')}><span className="promo-live-dot"/><span><b>{p.name}</b><small>{promoSummary(p,tenant)}</small></span><strong>{t('home.shop_offer')}</strong></button>)}</section>}
function promoSummary(p,tenant){if(p.promotion_type==='PERCENTAGE')return `${Number(p.value||0)}% off`;if(p.promotion_type==='FIXED_AMOUNT')return `${money(Number(p.value||0),tenant?.currency,tenant?.locale)} off`;if(p.promotion_type==='BOGO')return 'Buy more, get more';return 'Limited-time offer'}
function Hero({section,brand,tenant,experience,products,t}){const layout=section.type==='hero_slider'?'slider':experience?.layout?.hero||'split';if(layout==='slider')return <HeroSlider section={section} brand={brand} tenant={tenant} t={t}/>;if(layout==='featured_product')return <FeaturedHero section={section} brand={brand} tenant={tenant} product={findFeatured(section,products)} t={t}/>;if(layout==='video')return <VideoHero section={section} brand={brand} tenant={tenant} t={t}/>;return <StandardHero section={section} brand={brand} tenant={tenant} layout={layout} t={t}/>}
function storeNameOf(brand,tenant){return brand?.store_name||tenant?.name||'Luke Shop'}
function StandardHero({section,brand,tenant,layout,t}){const storeName=storeNameOf(brand,tenant);if(layout==='full_width'&&section.image_url)return <section className="hero server-driven hero-v3 hero-layout-full_width full-width-media-hero"><SafeImage className="full-width-hero-image" src={section.image_url} alt=""/><div className="full-width-hero-shade"/><HeroCopy section={section} brand={brand} storeName={storeName} t={t}/></section>;return <section className={`hero server-driven hero-v3 hero-layout-${layout} ${section.image_url?'with-campaign-media':'without-campaign-media'}`}><HeroCopy section={section} brand={brand} storeName={storeName} t={t}/>{section.image_url?<CampaignImage section={section} storeName={storeName}/>:layout!=='minimal'&&<EditorialPanel storeName={storeName}/>}</section>}
function HeroCopy({section,brand,storeName,t}){return <div className="hero-copy"><span className="eyebrow">{storeName} · Curated for you</span><h1>{section.title||brand?.hero_title||`Shop ${storeName}`}</h1><p>{section.body||brand?.hero_subtitle||'Discover what this store has to offer from one secure storefront.'}</p><div className="hero-actions"><button className="btn btn-primary" onClick={()=>go(section.cta_path||'/explore')}>{section.cta_label||t?.('home.explore_products')||'Explore products'}</button><SupportLauncher placement="home"/></div></div>}
function CampaignImage({section,storeName}){return <div className="campaign-media"><SafeImage className="hero-image" src={section.image_url} alt={section.title||storeName}/><div className="campaign-caption"><span>Featured campaign</span><strong>{section.title||storeName}</strong></div></div>}
function EditorialPanel({storeName}){return <div className="hero-panel editorial-panel"><div className="hero-visual-mark"><span>{storeName.slice(0,2).toUpperCase()}</span></div><div className="hero-stat"><strong>Discover the collection</strong><span>Browse new favorites selected by {storeName}.</span></div><div className="hero-stat"><strong>Order with confidence</strong><span>Secure checkout, order history and delivery milestones in one place.</span></div><div className="hero-trust-row"><span>Secure checkout</span><span>Order tracking</span><span>Support</span></div></div>}
function HeroSlider({section,brand,tenant,t}){const storeName=storeNameOf(brand,tenant);const slides=section.slides?.length?section.slides:[{id:'default',title:section.title||brand?.hero_title,body:section.body||brand?.hero_subtitle,image_url:section.image_url,cta_label:section.cta_label,cta_path:section.cta_path}];const[index,setIndex]=useState(0);useEffect(()=>{if(slides.length<2)return;const id=setInterval(()=>setIndex(v=>(v+1)%slides.length),5500);return()=>clearInterval(id)},[slides.length]);const slide=slides[index]||slides[0];return <section className="hero hero-slider-v3"><div className="hero-slider-stage">{slide.image_url&&<SafeImage src={slide.image_url} alt=""/>}<div className="hero-slider-overlay"/><div className="hero-slider-copy"><span className="eyebrow">{storeName} · {index+1}/{slides.length}</span><h1>{slide.title||`Shop ${storeName}`}</h1><p>{slide.body||'Discover the latest collection.'}</p><button className="btn btn-primary" onClick={()=>go(slide.cta_path||'/explore')}>{slide.cta_label||t?.('home.explore_products')||'Explore products'}</button></div></div>{slides.length>1&&<div className="hero-slider-controls">{slides.map((x,i)=><button key={x.id||i} className={i===index?'active':''} aria-label={`Show slide ${i+1}`} onClick={()=>setIndex(i)}/>)}</div>}</section>}
function findFeatured(section,products){return products.find(p=>p.public_id===section.product_ref)||products[0]||null}
function FeaturedHero({section,brand,tenant,product,t}){const storeName=storeNameOf(brand,tenant);if(!product)return <StandardHero section={section} brand={brand} tenant={tenant} layout="split" t={t}/>;return <section className="hero featured-product-hero"><div className="hero-copy"><span className="eyebrow">{storeName} · Featured product</span><h1>{section.title||product.name}</h1><p>{section.body||product.short_description||brand?.hero_subtitle||'A highlighted product selected for your storefront.'}</p><div className="featured-price">{money(Number(product.base_price||0),product.currency||tenant?.currency,tenant?.locale)}</div><button className="btn btn-primary" onClick={()=>go(`/product/${encodeURIComponent(product.slug)}`)}>{section.cta_label||t?.('home.view_product')||'View product'}</button></div><div className="featured-product-media">{product.primary_media_url?<SafeImage src={product.primary_media_url} alt={product.name} fallback={<div className="featured-placeholder">{product.name.slice(0,2).toUpperCase()}</div>}/>:<div className="featured-placeholder">{product.name.slice(0,2).toUpperCase()}</div>}</div></section>}
function VideoHero({section,brand,tenant,t}){const storeName=storeNameOf(brand,tenant);return <section className="hero video-hero-v3"><div className="video-hero-media">{section.video_url?<video src={section.video_url} poster={section.poster_url||section.image_url||undefined} autoPlay muted loop playsInline/>:section.image_url?<SafeImage className="video-fallback-image" src={section.image_url} alt=""/>:<div className="video-placeholder"/>}<div className="hero-video-shade"/></div><div className="video-hero-copy"><HeroCopy section={section} brand={brand} storeName={storeName} t={t}/></div></section>}
function CategorySection({section,categories,layout,t}){const limit=Number(section.limit||8);const shown=categories.slice(0,limit);return <section className={`section category-section category-layout-${layout||'cards'}`}><div className="section-head"><div><span className="eyebrow">{t?.('home.browse')||'Browse'}</span><h2>{section.title||t?.('home.shop_by_category')||'Shop by category'}</h2>{section.body&&<p>{section.body}</p>}</div><button className="link-btn" onClick={()=>go('/explore')}>{t?.('home.see_all')||'See all'}</button></div>{shown.length?<div className={`category-strip count-${Math.min(shown.length,4)}`}>{shown.map(c=><button key={c.public_id} onClick={()=>go('/explore',{category:c.slug})}><span className={`category-art ${c.image_url?'with-image':''}`} aria-hidden="true">{c.image_url?<SafeImage src={c.image_url} alt="" fallback={c.name.slice(0,2).toUpperCase()}/>:c.name.slice(0,2).toUpperCase()}</span><span className="category-kicker">Collection</span><strong>{c.name}</strong><span className="category-description">{c.description||'Browse products'}</span><b>Explore →</b></button>)}</div>:<Empty title="No categories yet" body="Published categories will appear here."/>}</section>}
function Products({section,products,title,layout}){const limit=Number(section.limit||8);return <section className={`section products-section products-layout-${layout||'four'}`}><div className="section-head"><div><span className="eyebrow">Shop</span><h2>{section.title||title}</h2>{section.body&&<p>{section.body}</p>}</div><button className="link-btn" onClick={()=>go('/explore')}>Browse all</button></div>{products.length?<div className="product-grid">{products.slice(0,limit).map(p=><ProductCard key={p.public_id} product={p}/>)}</div>:<Empty title="The storefront is being prepared" body="Published products will appear here."/>}</section>}
function Promo({section,active,tenant}){const title=section.title||active?.name||'Special offer';const body=section.body||promoSummary(active||{},tenant)||'Store promotions will appear here.';return <section className="section promo-section"><div>{section.image_url&&<SafeImage src={section.image_url} alt=""/>}<div><span className="eyebrow">Promotion</span><h2>{title}</h2><p>{body}</p><button className="btn btn-primary" onClick={()=>go(section.cta_path||'/explore')}>{section.cta_label||'Shop promotion'}</button></div></div></section>}
function HomeSkeleton(){return <div className="home-skeleton" aria-busy="true" aria-label="Loading storefront"><div className="hero-skeleton"><Skeleton w="30%" h={12}/><Skeleton w="70%" h={44} style={{marginTop:18}}/><Skeleton w="55%" h={18} style={{marginTop:16}}/><Skeleton w={180} h={46} r={999} style={{marginTop:26}}/></div><section className="section"><Skeleton w={160} h={22}/><div style={{marginTop:18}}><CategoryStripSkeleton count={6}/></div></section><section className="section"><Skeleton w={200} h={22}/><div style={{marginTop:18}}><ProductGridSkeleton count={8}/></div></section></div>;}

