import React,{useEffect,useMemo,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{go}from'../app/router.js';
import{Badge,Empty,Spinner,Toast,formatDate}from'../components/UI.jsx';
import{Icon}from'../components/icons.jsx';
import{useLocalization}from'../i18n/LocalizationContext.jsx';

const COPY={
 en:{eyebrow:'Digital purchases',title:'My library',subtitle:'View or download digital products you have purchased. Access is granted only after payment is confirmed.',empty:'Your library is empty',emptyBody:'Purchased digital images and videos will appear here after checkout.',shop:'Explore products',pending:'Payment verification pending',active:'Access active',revoked:'Access revoked',view:'View',download:'Download',downloads:'Downloads',unlimited:'Unlimited',files:'Protected files',noFiles:'No protected files were attached to this purchase.',order:'Order',purchased:'Purchased',viewOrder:'View order',viewProduct:'View product',close:'Close viewer',loading:'Loading your library…',openFailed:'Unable to open this protected file.',downloadFailed:'Unable to prepare this download.',viewOnly:'View only',downloadOnly:'Download only',viewDownload:'View + download',limitReached:'Download limit reached',remaining:'remaining'},
 my:{eyebrow:'ဒစ်ဂျစ်တယ်ဝယ်ယူမှု',title:'ကျွန်ုပ်၏ Library',subtitle:'ဝယ်ယူထားသော ဒစ်ဂျစ်တယ်ပစ္စည်းများကို ကြည့်ရန် သို့မဟုတ် ဒေါင်းလုဒ်လုပ်ရန်။ ငွေပေးချေမှု အတည်ပြုပြီးမှ အသုံးပြုခွင့်ရပါမည်။',empty:'Library တွင် ပစ္စည်းမရှိသေးပါ',emptyBody:'ဝယ်ယူထားသော ဒစ်ဂျစ်တယ်ပုံနှင့် ဗီဒီယိုများကို ငွေရှင်းပြီးနောက် ဤနေရာတွင် ပြသပါမည်။',shop:'ကုန်ပစ္စည်းများကြည့်ရန်',pending:'ငွေပေးချေမှု စစ်ဆေးနေသည်',active:'အသုံးပြုခွင့် ရရှိပြီး',revoked:'အသုံးပြုခွင့် ရုပ်သိမ်းထားသည်',view:'ကြည့်ရန်',download:'ဒေါင်းလုဒ်',downloads:'ဒေါင်းလုဒ်',unlimited:'အကန့်အသတ်မရှိ',files:'ကာကွယ်ထားသောဖိုင်များ',noFiles:'ဤဝယ်ယူမှုတွင် ကာကွယ်ထားသောဖိုင် မတွဲထားပါ။',order:'အော်ဒါ',purchased:'ဝယ်ယူချိန်',viewOrder:'အော်ဒါကြည့်ရန်',viewProduct:'ကုန်ပစ္စည်းကြည့်ရန်',close:'Viewer ပိတ်ရန်',loading:'Library ကို ဖွင့်နေသည်…',openFailed:'ကာကွယ်ထားသောဖိုင်ကို ဖွင့်မရပါ။',downloadFailed:'ဒေါင်းလုဒ် ပြင်ဆင်မရပါ။',viewOnly:'ကြည့်ရန်သာ',downloadOnly:'ဒေါင်းလုဒ်သာ',viewDownload:'ကြည့် + ဒေါင်းလုဒ်',limitReached:'ဒေါင်းလုဒ်အကန့်အသတ် ပြည့်ပါပြီ',remaining:'ကျန်'},
 id:{eyebrow:'Pembelian digital',title:'Perpustakaan saya',subtitle:'Lihat atau unduh produk digital yang telah Anda beli. Akses diberikan hanya setelah pembayaran dikonfirmasi.',empty:'Perpustakaan Anda kosong',emptyBody:'Gambar dan video digital yang dibeli akan muncul di sini setelah checkout.',shop:'Jelajahi produk',pending:'Verifikasi pembayaran tertunda',active:'Akses aktif',revoked:'Akses dicabut',view:'Lihat',download:'Unduh',downloads:'Unduhan',unlimited:'Tanpa batas',files:'File terlindungi',noFiles:'Tidak ada file terlindungi yang dilampirkan pada pembelian ini.',order:'Pesanan',purchased:'Dibeli',viewOrder:'Lihat pesanan',viewProduct:'Lihat produk',close:'Tutup penampil',loading:'Memuat perpustakaan…',openFailed:'Tidak dapat membuka file terlindungi ini.',downloadFailed:'Tidak dapat menyiapkan unduhan ini.',viewOnly:'Hanya lihat',downloadOnly:'Hanya unduh',viewDownload:'Lihat + unduh',limitReached:'Batas unduhan tercapai',remaining:'tersisa'}
};

const accessLabel=(mode,c)=>mode==='VIEW_ONLY'?c.viewOnly:mode==='DOWNLOAD_ONLY'?c.downloadOnly:c.viewDownload;
const mediaKind=asset=>String(asset?.mime_type||'').startsWith('video/')||String(asset?.media_type||'').toUpperCase()==='VIDEO'?'video':String(asset?.mime_type||'').startsWith('image/')||String(asset?.media_type||'').toUpperCase()==='IMAGE'?'image':'file';
const absoluteContentUrl=(api,path)=>new URL(path,`${api.baseUrl}/`).toString();

export function LibraryPage(){
 const{api,isAuthenticated}=useAuth();
 const{locale}=useLocalization();
 const c=COPY[locale]||COPY.en;
 const[items,setItems]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(''),[viewer,setViewer]=useState(null),[toast,setToast]=useState('');
 const load=async()=>{if(!isAuthenticated)return;setLoading(true);setError('');try{const r=await api.request('/v1/customer/library',{auth:true});setItems(r.data.library||[])}catch(e){setError(e.message||String(e))}finally{setLoading(false)}};
 useEffect(()=>{load()},[isAuthenticated]);
 const activeCount=useMemo(()=>items.filter(x=>x.status==='ACTIVE').length,[items]);
 const requestAccess=async(item,asset,mode)=>{const key=`${item.id}:${asset.id}:${mode}`;setBusy(key);setError('');try{const r=await api.request(`/v1/customer/library/${encodeURIComponent(item.id)}/assets/${encodeURIComponent(asset.id)}/access`,{method:'POST',auth:true,body:{mode}});const access=r.data.access;const url=absoluteContentUrl(api,access.content_path);if(mode==='VIEW'){setViewer({item,asset,access,url})}else{const a=document.createElement('a');a.href=url;a.rel='noopener';a.download=access.original_filename||asset.original_filename||'download';document.body.appendChild(a);a.click();a.remove();setToast(`${c.download}: ${access.original_filename||asset.original_filename||''}`);await load()}}catch(e){setError(e.message||(mode==='VIEW'?c.openFailed:c.downloadFailed))}finally{setBusy('')}};
 if(!isAuthenticated)return <section className="section digital-library-page"><Empty icon="lock" title="Sign in to open your library" body="Your purchased digital content is protected by your customer account." action={<button className="btn btn-primary" onClick={()=>go('/login',{next:'/library'})}>Sign in</button>}/></section>;
 if(loading)return <section className="section digital-library-page"><Spinner label={c.loading}/></section>;
 return <section className="section digital-library-page" data-testid="customer-digital-library">
  <div className="library-hero"><div><span className="eyebrow">{c.eyebrow}</span><h1>{c.title}</h1><p>{c.subtitle}</p></div><div className="library-count"><strong>{activeCount}</strong><span>{c.active}</span></div></div>
  {error&&<div className="form-error" role="alert">{error}</div>}
  {!items.length?<Empty icon="image" title={c.empty} body={c.emptyBody} action={<button className="btn btn-primary" onClick={()=>go('/explore')}>{c.shop}</button>}/>:<div className="digital-library-list">{items.map(item=>{
   const pending=item.status!=='ACTIVE';const limit=item.download_limit==null?null:Number(item.download_limit);const used=Number(item.download_count||0);const remaining=limit==null?null:Math.max(0,limit-used);return <article className={`digital-library-card ${pending?'is-pending':''}`} key={item.id}>
    <div className="library-card-head"><div><div className="library-title-row"><h2>{item.title_snapshot||item.product_name}</h2><Badge tone={pending?'warn':'good'}>{pending?c.pending:c.active}</Badge></div>{item.variant_title_snapshot&&<p className="muted">{item.variant_title_snapshot}</p>}<div className="library-meta"><span><Icon name="receipt" size={14}/> {c.order} {item.order_number||item.order_id}</span><span><Icon name="clock" size={14}/> {c.purchased} {formatDate(item.purchased_at,locale)}</span></div></div><Badge>{accessLabel(item.access_mode,c)}</Badge></div>
    <div className="library-entitlement-strip"><span>{c.downloads}: <strong>{limit==null?c.unlimited:`${used}/${limit}`}</strong></span>{remaining!==null&&<span className={remaining===0?'library-limit-hit':''}>{remaining===0?c.limitReached:`${remaining} ${c.remaining}`}</span>}</div>
    <div className="library-files"><strong>{c.files}</strong>{item.assets?.length?<div className="library-file-grid">{item.assets.map(asset=>{const kind=mediaKind(asset);const viewBusy=busy===`${item.id}:${asset.id}:VIEW`;const downloadBusy=busy===`${item.id}:${asset.id}:DOWNLOAD`;return <div className="library-file" key={asset.id}><div className="library-file-icon"><Icon name={kind==='video'?'play':'image'} size={20}/></div><div className="library-file-copy"><strong>{asset.original_filename||'Protected content'}</strong><small>{asset.mime_type||asset.media_type||'Digital content'}</small></div><div className="library-file-actions">{item.can_view&&<button className="btn btn-secondary btn-small" disabled={viewBusy||pending} onClick={()=>requestAccess(item,asset,'VIEW')}>{viewBusy?'…':c.view}</button>}{item.can_download&&<button className="btn btn-primary btn-small" disabled={downloadBusy||pending||remaining===0} onClick={()=>requestAccess(item,asset,'DOWNLOAD')}>{downloadBusy?'…':c.download}</button>}</div></div>})}</div>:<p className="muted">{c.noFiles}</p>}</div>
    <div className="library-card-actions">{item.product_slug&&<button className="link-btn" onClick={()=>go(`/product/${encodeURIComponent(item.product_slug)}`)}>{c.viewProduct}</button>}<button className="link-btn" onClick={()=>go(`/orders/${encodeURIComponent(item.order_number||item.order_id)}`)}>{c.viewOrder}</button></div>
   </article>})}</div>}
  {viewer&&<div className="library-viewer-backdrop" role="dialog" aria-modal="true" aria-label={viewer.asset.original_filename||c.view}><div className="library-viewer"><div className="library-viewer-head"><div><strong>{viewer.item.title_snapshot||viewer.item.product_name}</strong><small>{viewer.asset.original_filename}</small></div><button className="icon-btn" aria-label={c.close} onClick={()=>setViewer(null)}>×</button></div><div className="library-viewer-stage">{mediaKind(viewer.asset)==='video'?<video src={viewer.url} controls playsInline preload="metadata"/>:mediaKind(viewer.asset)==='image'?<img src={viewer.url} alt={viewer.item.title_snapshot||viewer.item.product_name||''}/>:<div className="library-file-fallback"><Icon name="file" size={32}/><p>{viewer.asset.original_filename}</p></div>}</div></div></div>}
  <Toast message={toast} onClose={()=>setToast('')}/>
 </section>;
}
