import React,{useEffect,useMemo,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{useStore}from'../store/StoreContext.jsx';
import{Empty,Badge,Spinner,Toast,formatDate}from'../components/UI.jsx';
import{SupportLauncher}from'../components/SupportLauncher.jsx';
import{LocationCapture}from'../components/DeliveryLocation.jsx';
import{go}from'../app/router.js';

const blankAddress={label:'Home',recipient_name:'',phone:'',country_code:'',state:'',city:'',postal_code:'',address_line_1:'',address_line_2:'',delivery_note:'',is_default:false,latitude:null,longitude:null,accuracy_meters:null,location_source:null,location_updated_at:null};
const cloneAddress=a=>({...blankAddress,...a,country_code:a?.country_code||''});

export function ProfilePage(){
 const{session,isAuthenticated,api,refreshProfile,logout}=useAuth();const{tenant}=useStore();
 const[loading,setLoading]=useState(true),[error,setError]=useState(''),[toast,setToast]=useState('');
 const[addresses,setAddresses]=useState([]),[sessions,setSessions]=useState([]),[addressOpen,setAddressOpen]=useState(false),[addressForm,setAddressForm]=useState(blankAddress),[editingAddress,setEditingAddress]=useState('');
 const[name,setName]=useState(''),[password,setPassword]=useState({current_password:'',new_password:'',confirm:''}),[busy,setBusy]=useState('');
 const customer=session?.customer;
 const currentSession=useMemo(()=>sessions.find(s=>s.current),[sessions]);
 const load=async()=>{if(!isAuthenticated){setLoading(false);return;}setError('');try{const[profile,a,s]=await Promise.all([refreshProfile(),api.request('/v1/customer/me/addresses',{auth:true}),api.request('/v1/customer/me/sessions',{auth:true})]);setName(profile?.customer?.display_name||profile?.customer?.name||session?.customer?.display_name||'');setAddresses(a.data.addresses||[]);setSessions(s.data.sessions||[])}catch(e){setError(e.message||'Unable to load account')}finally{setLoading(false)}};
 useEffect(()=>{load()},[isAuthenticated]);
 useEffect(()=>{if(customer?.display_name)setName(customer.display_name)},[customer?.display_name]);
 if(!isAuthenticated)return <section className="section"><Empty title="Sign in to view your profile" action={<button className="btn btn-primary" onClick={()=>go('/login',{next:'/profile'})}>Sign in</button>}/></section>;
 if(loading)return <Spinner label="Loading account…"/>;
 const saveProfile=async e=>{e.preventDefault();setBusy('profile');setError('');try{await api.request('/v1/customer/me',{method:'PATCH',body:{display_name:name.trim()},auth:true});await refreshProfile();setToast('Profile updated')}catch(x){setError(x.message)}finally{setBusy('')}};
 const savePassword=async e=>{e.preventDefault();if(password.new_password!==password.confirm){setError('New passwords do not match');return;}setBusy('password');setError('');try{await api.request('/v1/customer/me/change-password',{method:'POST',body:{current_password:password.current_password,new_password:password.new_password},auth:true});setPassword({current_password:'',new_password:'',confirm:''});setToast('Password changed. Other sessions were signed out.');await load()}catch(x){setError(x.message)}finally{setBusy('')}};
 const openNew=()=>{setEditingAddress('');setAddressForm({...blankAddress,is_default:addresses.length===0});setAddressOpen(true)};
 const openEdit=a=>{setEditingAddress(a.id);setAddressForm(cloneAddress(a));setAddressOpen(true)};
 const saveAddress=async e=>{e.preventDefault();setBusy('address');setError('');try{const body={...addressForm,label:addressForm.label.trim(),recipient_name:addressForm.recipient_name.trim(),country_code:addressForm.country_code.trim().toUpperCase(),city:addressForm.city.trim(),address_line_1:addressForm.address_line_1.trim(),phone:addressForm.phone||null,state:addressForm.state||null,postal_code:addressForm.postal_code||null,address_line_2:addressForm.address_line_2||null,delivery_note:addressForm.delivery_note||null};if(editingAddress)await api.request(`/v1/customer/me/addresses/${encodeURIComponent(editingAddress)}`,{method:'PATCH',body,auth:true});else await api.request('/v1/customer/me/addresses',{method:'POST',body,auth:true});setAddressOpen(false);setToast(editingAddress?'Address updated':'Address saved');await load()}catch(x){setError(x.message)}finally{setBusy('')}};
 const removeAddress=async a=>{if(!confirm(`Remove ${a.label||'this address'}?`))return;setBusy(`address-${a.id}`);setError('');try{await api.request(`/v1/customer/me/addresses/${encodeURIComponent(a.id)}`,{method:'DELETE',auth:true});setToast('Address removed');await load()}catch(x){setError(x.message)}finally{setBusy('')}};
 const makeDefault=async a=>{setBusy(`address-${a.id}`);setError('');try{await api.request(`/v1/customer/me/addresses/${encodeURIComponent(a.id)}`,{method:'PATCH',body:{is_default:true},auth:true});setToast('Default address updated');await load()}catch(x){setError(x.message)}finally{setBusy('')}};
 const revokeSession=async s=>{if(s.current)return;setBusy(`session-${s.id}`);setError('');try{await api.request(`/v1/customer/me/sessions/${encodeURIComponent(s.id)}`,{method:'DELETE',auth:true});setToast('Session revoked');await load()}catch(x){setError(x.message)}finally{setBusy('')}};
 const revokeOthers=async()=>{setBusy('sessions');setError('');try{const d=await api.request('/v1/customer/me/sessions/revoke-others',{method:'POST',body:{},auth:true});setToast(`${d.data.sessions_revoked||0} other session(s) revoked`);await load()}catch(x){setError(x.message)}finally{setBusy('')}};
 return <section className="section profile-page-v2">
  <div className="section-head"><div><span className="eyebrow">Account</span><h1>Profile & security</h1></div></div>
  {error&&<div className="form-error account-error">{error}</div>}
  <div className="account-overview"><div className="profile-card"><div className="avatar">{customer?.display_name?.slice(0,1)?.toUpperCase()||'C'}</div><div><h2>{customer?.display_name}</h2><p>{customer?.email}</p><Badge tone={customer?.status==='ACTIVE'?'good':'warn'}>{customer?.status}</Badge></div></div><div className="account-context"><div><span>Customer ID</span><strong>{customer?.id||'—'}</strong></div><div><span>Store currency</span><strong>{tenant?.currency||'—'}</strong></div><div><span>Locale</span><strong>{tenant?.locale||'—'}</strong></div><div><span>Active sessions</span><strong>{sessions.length}</strong></div></div></div>
  <div className="account-grid">
   <div className="form-card"><h2>Personal information</h2><p className="muted">This name is used for your customer account and order contact details.</p><form onSubmit={saveProfile}><label>Display name<input required maxLength="100" value={name} onChange={e=>setName(e.target.value)}/></label><label>Email<input readOnly value={customer?.email||''}/></label><button className="btn btn-primary" disabled={busy==='profile'}>{busy==='profile'?'Saving…':'Save profile'}</button></form></div>
   <div className="form-card"><div className="card-title-row"><div><h2>Saved addresses</h2><p className="muted">Use saved addresses during checkout.</p></div><button className="btn btn-secondary btn-small" onClick={openNew}>Add address</button></div>{addresses.length?<div className="address-list">{addresses.map(a=><article className={`address-card ${a.is_default?'default':''}`} key={a.id}><div className="address-card-head"><div><strong>{a.label}</strong>{a.is_default&&<Badge tone="good">Default</Badge>}</div><div className="address-actions"><button className="link-btn" onClick={()=>openEdit(a)}>Edit</button>{!a.is_default&&<button className="link-btn" disabled={busy===`address-${a.id}`} onClick={()=>makeDefault(a)}>Make default</button>}<button className="link-btn danger-link" disabled={busy===`address-${a.id}`} onClick={()=>removeAddress(a)}>Remove</button></div></div><p>{a.recipient_name}{a.phone?` · ${a.phone}`:''}</p><p>{[a.address_line_1,a.address_line_2,a.city,a.state,a.postal_code,a.country_code].filter(Boolean).join(', ')}</p>{a.delivery_note&&<small>Delivery note: {a.delivery_note}</small>}{a.latitude!=null&&a.longitude!=null&&<small className="address-location-saved">📍 Precise location saved · {a.accuracy_meters!=null?`±${Math.round(a.accuracy_meters)} m`:'GPS'}</small>}</article>)}</div>:<div className="account-empty">No saved addresses yet.</div>}</div>
   <div className="form-card"><h2>Change password</h2><p className="muted">Use at least 12 characters. Changing your password revokes your other active sessions.</p><form onSubmit={savePassword}><label>Current password<input type="password" minLength="12" required autoComplete="current-password" value={password.current_password} onChange={e=>setPassword({...password,current_password:e.target.value})}/></label><label>New password<input type="password" minLength="12" required autoComplete="new-password" value={password.new_password} onChange={e=>setPassword({...password,new_password:e.target.value})}/></label><label>Confirm new password<input type="password" minLength="12" required autoComplete="new-password" value={password.confirm} onChange={e=>setPassword({...password,confirm:e.target.value})}/></label><button className="btn btn-primary" disabled={busy==='password'}>{busy==='password'?'Changing…':'Change password'}</button></form></div>
   <div className="form-card"><div className="card-title-row"><div><h2>Active sessions</h2><p className="muted">Review devices currently signed in to this customer account.</p></div>{sessions.some(s=>!s.current)&&<button className="btn btn-secondary btn-small" disabled={busy==='sessions'} onClick={revokeOthers}>Sign out others</button>}</div><div className="session-list">{sessions.map(s=><div className="session-row" key={s.id}><div><strong>{s.current?'This session':'Signed-in session'}</strong><span>{s.user_agent||'Unknown browser'}</span><small>{s.request_ip||'Unknown IP'} · Last active {formatDate(s.last_seen_at,tenant?.locale)}</small></div>{s.current?<Badge tone="good">Current</Badge>:<button className="btn btn-secondary btn-small" disabled={busy===`session-${s.id}`} onClick={()=>revokeSession(s)}>Revoke</button>}</div>)}</div>{currentSession&&<small className="muted">Current session expires {formatDate(currentSession.expires_at,tenant?.locale)}.</small>}</div>
   <div className="form-card"><h2>Support</h2><p>Get help with your account or an order when customer support is enabled by this store.</p><SupportLauncher placement="profile"/></div>
   <div className="form-card danger-zone"><h2>Sign out</h2><p className="muted">End this browser session without affecting other devices.</p><button className="btn btn-secondary" onClick={logout}>Sign out</button></div>
  </div>
  {addressOpen&&<div className="customer-modal-bg" onMouseDown={e=>e.target===e.currentTarget&&setAddressOpen(false)}><div className="customer-modal"><div className="customer-modal-head"><div><span className="eyebrow">Address book</span><h2>{editingAddress?'Edit address':'Add address'}</h2></div><button className="modal-close" onClick={()=>setAddressOpen(false)}>×</button></div><form onSubmit={saveAddress} className="form-grid"><label>Label<input required maxLength="80" placeholder="Home" value={addressForm.label} onChange={e=>setAddressForm({...addressForm,label:e.target.value})}/></label><label>Recipient<input required value={addressForm.recipient_name} onChange={e=>setAddressForm({...addressForm,recipient_name:e.target.value})}/></label><label>Phone<input value={addressForm.phone} onChange={e=>setAddressForm({...addressForm,phone:e.target.value})}/></label><label>Country code<input required maxLength="2" placeholder="US" value={addressForm.country_code} onChange={e=>setAddressForm({...addressForm,country_code:e.target.value.toUpperCase()})}/></label><label>State / region<input value={addressForm.state} onChange={e=>setAddressForm({...addressForm,state:e.target.value})}/></label><label>City<input required value={addressForm.city} onChange={e=>setAddressForm({...addressForm,city:e.target.value})}/></label><label>Postal code<input value={addressForm.postal_code} onChange={e=>setAddressForm({...addressForm,postal_code:e.target.value})}/></label><label className="span-2">Address line 1<input required value={addressForm.address_line_1} onChange={e=>setAddressForm({...addressForm,address_line_1:e.target.value})}/></label><label className="span-2">Address line 2<input value={addressForm.address_line_2} onChange={e=>setAddressForm({...addressForm,address_line_2:e.target.value})}/></label><label className="span-2">Delivery note<textarea value={addressForm.delivery_note} onChange={e=>setAddressForm({...addressForm,delivery_note:e.target.value})}/></label><div className="span-2"><LocationCapture value={addressForm} onChange={loc=>setAddressForm({...addressForm,...loc})}/></div><label className="checkbox-line span-2"><input type="checkbox" checked={Boolean(addressForm.is_default)} onChange={e=>setAddressForm({...addressForm,is_default:e.target.checked})}/><span>Use as default delivery address</span></label><div className="modal-actions span-2"><button type="button" className="btn btn-secondary" onClick={()=>setAddressOpen(false)}>Cancel</button><button className="btn btn-primary" disabled={busy==='address'}>{busy==='address'?'Saving…':'Save address'}</button></div></form></div></div>}
  <Toast message={toast} onClose={()=>setToast('')}/>
 </section>;
}
