import React,{useEffect,useId,useRef,useState}from'react';
import{Icon}from'./icons.jsx';

export const PHONE_COUNTRIES={
 KH:{name:'Cambodia',calling:'+855',flag:'🇰🇭'},IN:{name:'India',calling:'+91',flag:'🇮🇳'},MM:{name:'Myanmar',calling:'+95',flag:'🇲🇲'},ID:{name:'Indonesia',calling:'+62',flag:'🇮🇩'},PH:{name:'Philippines',calling:'+63',flag:'🇵🇭'},TH:{name:'Thailand',calling:'+66',flag:'🇹🇭'},VN:{name:'Vietnam',calling:'+84',flag:'🇻🇳'},MY:{name:'Malaysia',calling:'+60',flag:'🇲🇾'},SG:{name:'Singapore',calling:'+65',flag:'🇸🇬'},US:{name:'United States',calling:'+1',flag:'🇺🇸'},GB:{name:'United Kingdom',calling:'+44',flag:'🇬🇧'}
};
let googlePromise;
function loadGoogle(){if(window.google?.accounts?.id)return Promise.resolve();if(!googlePromise)googlePromise=new Promise((resolve,reject)=>{const old=document.querySelector('script[data-luke-google]');if(old){old.addEventListener('load',resolve,{once:true});old.addEventListener('error',reject,{once:true});return;}const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;s.defer=true;s.dataset.lukeGoogle='1';s.onload=resolve;s.onerror=()=>reject(new Error('Google sign-in could not load'));document.head.appendChild(s);});return googlePromise;}
export function GoogleAuthButton({clientId,onCredential,label='Continue with Google',disabled=false}){const ref=useRef(null),[error,setError]=useState('');useEffect(()=>{let active=true;if(!clientId||disabled)return;loadGoogle().then(()=>{if(!active||!ref.current)return;ref.current.innerHTML='';window.google.accounts.id.initialize({client_id:clientId,callback:r=>r?.credential&&onCredential?.(r.credential)});window.google.accounts.id.renderButton(ref.current,{theme:'outline',size:'large',shape:'rectangular',text:'continue_with',width:320});}).catch(e=>active&&setError(e.message));return()=>{active=false}},[clientId,disabled,onCredential]);if(!clientId)return null;return <div className="external-auth-method"><div ref={ref} className="google-auth-slot" aria-label={label}/>{error&&<small className="form-error">{error}</small>}</div>}

export function TelegramAuthButton({botUsername,onAuth,label='Continue with Telegram'}){const ref=useRef(null),id=useId().replace(/:/g,''),[error,setError]=useState('');useEffect(()=>{if(!botUsername||!ref.current)return;const fn=`lukeTelegram_${id}`;window[fn]=user=>onAuth?.(user);ref.current.innerHTML='';const script=document.createElement('script');script.async=true;script.src='https://telegram.org/js/telegram-widget.js?22';script.setAttribute('data-telegram-login',botUsername);script.setAttribute('data-size','large');script.setAttribute('data-radius','8');script.setAttribute('data-request-access','write');script.setAttribute('data-userpic','false');script.setAttribute('data-onauth',`${fn}(user)`);script.onerror=()=>setError('Telegram sign-in could not load');ref.current.appendChild(script);return()=>{delete window[fn];if(ref.current)ref.current.innerHTML=''}},[botUsername,id,onAuth]);if(!botUsername)return null;return <div className="external-auth-method"><div className="telegram-auth-slot"><span className="sr-only">{label}</span><div ref={ref}/></div>{error&&<small className="form-error">{error}</small>}</div>}

export function PhoneOtpPanel({countries=[],onRequest,onVerify,title='Continue with phone',verifyLabel='Verify & continue'}){const available=(countries.length?countries:['KH','IN','MM','ID']).filter(c=>PHONE_COUNTRIES[c]);const[country,setCountry]=useState(available[0]||'KH'),[phone,setPhone]=useState(''),[challenge,setChallenge]=useState(null),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const meta=PHONE_COUNTRIES[country]||PHONE_COUNTRIES.KH;
 const request=async()=>{setBusy(true);setError('');try{const r=await onRequest({country_code:country,calling_code:meta.calling,phone_number:phone});setChallenge(r);setCode('')}catch(e){setError(e.message)}finally{setBusy(false)}};
 const verify=async()=>{setBusy(true);setError('');try{await onVerify({challenge_id:challenge.challenge_id,code});}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <div className="phone-auth-panel"><strong><Icon name="phone" size={17}/> {title}</strong>{!challenge?<div className="phone-auth-row"><select aria-label="Country code" value={country} onChange={e=>setCountry(e.target.value)}>{available.map(c=><option key={c} value={c}>{PHONE_COUNTRIES[c].flag} {PHONE_COUNTRIES[c].name} {PHONE_COUNTRIES[c].calling}</option>)}</select><input inputMode="tel" autoComplete="tel-national" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone number"/><button type="button" className="btn btn-secondary" disabled={busy||phone.replace(/\D/g,'').length<5} onClick={request}>{busy?'Sending…':'Send code'}</button></div>:<div className="phone-verify"><small>Code sent to {challenge.phone_masked}</small><div className="phone-auth-row"><input inputMode="numeric" autoComplete="one-time-code" maxLength="6" pattern="[0-9]{6}" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="6-digit code"/><button type="button" className="btn btn-primary" disabled={busy||code.length!==6} onClick={verify}>{busy?'Verifying…':verifyLabel}</button></div><button type="button" className="link-btn" onClick={()=>setChallenge(null)}>Use another number</button></div>}{error&&<div className="form-error">{error}</div>}</div>}
