import React,{useEffect,useId,useRef,useState}from'react';
import{Icon}from'./icons.jsx';

export const PHONE_COUNTRIES={
 KH:{name:'Cambodia',calling:'+855',flag:'🇰🇭'},IN:{name:'India',calling:'+91',flag:'🇮🇳'},MM:{name:'Myanmar',calling:'+95',flag:'🇲🇲'},ID:{name:'Indonesia',calling:'+62',flag:'🇮🇩'},PH:{name:'Philippines',calling:'+63',flag:'🇵🇭'},TH:{name:'Thailand',calling:'+66',flag:'🇹🇭'},VN:{name:'Vietnam',calling:'+84',flag:'🇻🇳'},MY:{name:'Malaysia',calling:'+60',flag:'🇲🇾'},SG:{name:'Singapore',calling:'+65',flag:'🇸🇬'},US:{name:'United States',calling:'+1',flag:'🇺🇸'},GB:{name:'United Kingdom',calling:'+44',flag:'🇬🇧'}
};

let googlePromise;
function loadGoogle(){if(window.google?.accounts?.id)return Promise.resolve();if(!googlePromise)googlePromise=new Promise((resolve,reject)=>{const old=document.querySelector('script[data-luke-google]');if(old){old.addEventListener('load',resolve,{once:true});old.addEventListener('error',reject,{once:true});return;}const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;s.defer=true;s.dataset.lukeGoogle='1';s.onload=resolve;s.onerror=()=>reject(new Error('Google sign-in could not load'));document.head.appendChild(s);});return googlePromise;}
export function GoogleAuthButton({clientId,onCredential,label='Continue with Google',disabled=false,compact=false}){const ref=useRef(null),[error,setError]=useState('');useEffect(()=>{let active=true;if(!clientId||disabled)return;loadGoogle().then(()=>{if(!active||!ref.current)return;ref.current.innerHTML='';window.google.accounts.id.initialize({client_id:clientId,callback:r=>r?.credential&&onCredential?.(r.credential)});window.google.accounts.id.renderButton(ref.current,compact?{type:'icon',theme:'outline',size:'large',shape:'circle'}:{theme:'outline',size:'large',shape:'rectangular',text:'continue_with',logo_alignment:'left',width:336});}).catch(e=>active&&setError(e.message));return()=>{active=false}},[clientId,disabled,onCredential,compact]);if(!clientId)return null;return <div className={`external-auth-method google-provider${compact?' social-provider-compact':''}`}><div ref={ref} className={`google-auth-slot${compact?' google-auth-slot-compact':''}`} aria-label={label}/>{compact&&<span className="provider-name">Google</span>}{error&&<small className="form-error">{error}</small>}</div>}

let telegramPromise;
function loadTelegramModern(){if(window.Telegram?.Login?.auth)return Promise.resolve();if(!telegramPromise)telegramPromise=new Promise((resolve,reject)=>{const old=document.querySelector('script[data-luke-telegram-modern]');if(old){old.addEventListener('load',resolve,{once:true});old.addEventListener('error',reject,{once:true});return;}const s=document.createElement('script');s.src='https://oauth.telegram.org/js/telegram-login.js?5';s.async=true;s.defer=true;s.dataset.lukeTelegramModern='1';s.onload=resolve;s.onerror=()=>reject(new Error('Telegram sign-in could not load'));document.head.appendChild(s);});return telegramPromise;}
function TelegramMark(){return <svg className="telegram-brand-mark" aria-hidden="true" viewBox="0 0 48 48" width="28" height="28"><circle cx="24" cy="24" r="24" fill="#229ED9"/><path fill="#fff" d="M35.6 14.2 31.4 34c-.32 1.4-1.16 1.75-2.35 1.09l-6.43-4.73-3.1 2.96c-.34.34-.63.63-1.29.63l.46-6.52 11.92-10.7c.52-.46-.11-.72-.8-.26L15.1 25.7l-6.35-1.98c-1.38-.43-1.4-1.38.3-2.03l24.8-9.47c1.15-.42 2.15.27 1.75 1.98Z"/></svg>}
export function TelegramAuthButton({clientId,botUsername,mode='OIDC_LIBRARY',nonceLoader,onAuth,label='Continue with Telegram',disabled=false,compact=false}){const ref=useRef(null),id=useId().replace(/:/g,''),[error,setError]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{if(mode!=='LEGACY_WIDGET'||!botUsername||!ref.current)return;const fn=`lukeTelegram_${id}`;window[fn]=user=>onAuth?.(user);ref.current.innerHTML='';const script=document.createElement('script');script.async=true;script.src='https://telegram.org/js/telegram-widget.js?22';script.setAttribute('data-telegram-login',botUsername);script.setAttribute('data-size',compact?'small':'large');script.setAttribute('data-radius',compact?'20':'8');script.setAttribute('data-userpic','false');script.setAttribute('data-onauth',`${fn}(user)`);script.onerror=()=>setError('Telegram sign-in could not load');ref.current.appendChild(script);return()=>{delete window[fn];if(ref.current)ref.current.innerHTML=''}},[mode,botUsername,id,onAuth,compact]);
 const open=async()=>{setBusy(true);setError('');try{await loadTelegramModern();const nonce=await nonceLoader?.();if(!nonce)throw new Error('Could not start a secure Telegram sign-in session');window.Telegram.Login.auth({client_id:Number(clientId),scope:['profile'],nonce},data=>{setBusy(false);if(data?.error){setError(data.error);return;}if(!data?.id_token){setError('Telegram did not return a verified login token');return;}onAuth?.({id_token:data.id_token,nonce});});}catch(e){setBusy(false);setError(e.message||'Telegram sign-in could not start')}};
 if(mode==='LEGACY_WIDGET'&&botUsername)return <div className={`external-auth-method telegram-auth-slot${compact?' social-provider-compact':''}`}><span className="sr-only">{label}</span><div ref={ref}/>{compact&&<span className="provider-name">Telegram</span>}{error&&<small className="form-error">{error}</small>}</div>;
 if(!clientId)return null;
 return <div className={`external-auth-method telegram-provider${compact?' social-provider-compact':''}`}><button type="button" className={`telegram-login-button${compact?' telegram-login-button-compact':''}`} onClick={open} disabled={disabled||busy} aria-label={label}><TelegramMark/>{!compact&&<span>{busy?'Opening Telegram…':label}</span>}</button>{compact&&<span className="provider-name">{busy?'Opening…':'Telegram'}</span>}{error&&<small className="form-error">{error}</small>}</div>;
}

let turnstilePromise;
function loadTurnstile(){if(window.turnstile?.render)return Promise.resolve();if(!turnstilePromise)turnstilePromise=new Promise((resolve,reject)=>{const old=document.querySelector('script[data-luke-turnstile]');if(old){old.addEventListener('load',resolve,{once:true});old.addEventListener('error',reject,{once:true});return;}const s=document.createElement('script');s.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';s.async=true;s.defer=true;s.dataset.lukeTurnstile='1';s.onload=resolve;s.onerror=()=>reject(new Error('Cloudflare security verification could not load'));document.head.appendChild(s);});return turnstilePromise;}
export function TurnstileWidget({siteKey,action,onToken,resetSignal=0,appearance='always',size='flexible',showNote=true,className=''}){const ref=useRef(null),widget=useRef(null),[error,setError]=useState('');useEffect(()=>{let active=true;if(!siteKey)return;loadTurnstile().then(()=>{if(!active||!ref.current)return;if(widget.current!=null){try{window.turnstile.remove(widget.current)}catch{}widget.current=null}ref.current.innerHTML='';widget.current=window.turnstile.render(ref.current,{sitekey:siteKey,action,theme:'auto',size,appearance,callback:token=>{setError('');onToken?.(token)},'expired-callback':()=>onToken?.(''),'timeout-callback':()=>onToken?.(''),'error-callback':()=>{setError('Security verification needs to be refreshed');onToken?.('')}});}).catch(e=>active&&setError(e.message));return()=>{active=false;if(widget.current!=null&&window.turnstile?.remove){try{window.turnstile.remove(widget.current)}catch{}widget.current=null}}},[siteKey,action,resetSignal,appearance,size]);if(!siteKey)return null;return <div className={`turnstile-shell ${className}`.trim()}><div ref={ref}/>{error&&<small className="form-error">{error}</small>}{showNote&&<small className="turnstile-note">Protected by Cloudflare Turnstile</small>}</div>}

export function PhoneOtpPanel({countries=[],onRequest,onVerify,title='Continue with phone',verifyLabel='Verify & continue'}){const available=(countries.length?countries:['KH','IN','MM','ID']).filter(c=>PHONE_COUNTRIES[c]);const[country,setCountry]=useState(available[0]||'KH'),[phone,setPhone]=useState(''),[challenge,setChallenge]=useState(null),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const meta=PHONE_COUNTRIES[country]||PHONE_COUNTRIES.KH;
 const request=async()=>{setBusy(true);setError('');try{const r=await onRequest({country_code:country,calling_code:meta.calling,phone_number:phone});setChallenge(r);setCode('')}catch(e){setError(e.message)}finally{setBusy(false)}};
 const verify=async()=>{setBusy(true);setError('');try{await onVerify({challenge_id:challenge.challenge_id,code});}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <div className="phone-auth-panel"><strong><Icon name="phone" size={17}/> {title}</strong>{!challenge?<div className="phone-auth-row"><select aria-label="Country code" value={country} onChange={e=>setCountry(e.target.value)}>{available.map(c=><option key={c} value={c}>{PHONE_COUNTRIES[c].flag} {PHONE_COUNTRIES[c].name} {PHONE_COUNTRIES[c].calling}</option>)}</select><input inputMode="tel" autoComplete="tel-national" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone number"/><button type="button" className="btn btn-secondary" disabled={busy||phone.replace(/\D/g,'').length<5} onClick={request}>{busy?'Sending…':'Send code'}</button></div>:<div className="phone-verify"><small>Code sent to {challenge.phone_masked}</small><div className="phone-auth-row"><input inputMode="numeric" autoComplete="one-time-code" maxLength="6" pattern="[0-9]{6}" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="6-digit code"/><button type="button" className="btn btn-primary" disabled={busy||code.length!==6} onClick={verify}>{busy?'Verifying…':verifyLabel}</button></div><button type="button" className="link-btn" onClick={()=>setChallenge(null)}>Use another number</button></div>}{error&&<div className="form-error">{error}</div>}</div>}
